# Generated by Django 3.0.14 on 2022-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
