# Generated by Django 4.1 on 2022-08-16 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0002_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='products1',
        ),
    ]
