# Generated by Django 4.1 on 2022-08-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0003_rename_products_products1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products1',
            new_name='products',
        ),
    ]
