# Generated by Django 4.1 on 2022-08-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0004_rename_products1_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='products2',
        ),
    ]
