# Generated by Django 4.1 on 2022-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0006_alter_products2_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products2',
            new_name='products',
        ),
    ]
