# Generated by Django 4.1 on 2022-08-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0007_rename_products2_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='items',
        ),
    ]
