# Generated by Django 4.1 on 2022-08-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0008_rename_products_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='products',
        ),
    ]
