# Generated by Django 4.1 on 2022-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('develop', '0011_products_imagepath_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagepath', models.FileField(default='', upload_to='develop/static/images/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='imagepath',
        ),
    ]
